using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class cameraMovement : MonoBehaviour
{
    private float mouseX;
    private float mouseY;

    public float mouseSensitivity = 100.0f;
    public float xRotation = 0.0f;

    public Transform character;

    // Start is called before the first frame update
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        mouseX = Input.GetAxis("Mouse X") * mouseSensitivity * Time.deltaTime;
        mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * Time.deltaTime;

        xRotation -= mouseY;
        xRotation = Mathf.Clamp(xRotation,-90.0f,90.0f);

        transform.localRotation = Quaternion.Euler(xRotation,0.0f,0.0f);

        character.Rotate(Vector3.up * mouseX);
    }
}
